server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          uri: https://github.com/jpollard-github/cns-config-repo
